DATA SEGMENT
BUF DB 'WORD.....$'
DATA ENDS
STACK SEGMENT PARA STACK 'STACK'
DW 20 DUP(?)
STACK ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA,SS:STACK
START:MOV AX,DATA
MOV DS,AX
LEA DX,BUF;取BUF字符串的偏移地址
MOV AH,9
INT 21H;调用9号功能显示字符串"WORD....."到屏幕
MOV AH,4CH
INT 21H
CODE ENDS
END START
